name: Test setup (version from file)

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - "**.md"

jobs:
 basic:
    name: Node from input ${{ matrix.node-version}} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
  nvmrc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    name: Node from nvmrc on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version-file: '.nvmrc'
  volta:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    name: Node from volta on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version-file: 'package.json'
  toolversions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    name: Node from toolversions on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version-file: '.tool-versions'
  
